<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Date range field day count attendance report</name>
   <tag></tag>
   <elementGuidId>e2477379-c6cc-4498-9e5f-9b98bb60bd6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reportrange</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reportrange']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b8380be-900a-4f47-9f3e-0b0f747c5463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe0b041c-70ab-4703-9b29-1b349cc46dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reportrange</value>
      <webElementGuid>f92e1448-071f-4316-bd3f-f99debb2eba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>reportrange</value>
      <webElementGuid>c2eea262-2c4e-42e1-b44b-7978b2afe436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reportrange&quot;)</value>
      <webElementGuid>6c396a14-a3b4-4ee5-83b6-3815625d43fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reportrange']</value>
      <webElementGuid>5533a5c3-10b2-4567-89f8-2518a8b0bb7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[15]/div/div/div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>8592f0ce-30ac-4587-80c2-1261a544c84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/input</value>
      <webElementGuid>23137aa0-bb91-4ab7-9fa9-f79c1ef8ea11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'reportrange']</value>
      <webElementGuid>8879e7c3-0757-4ddc-bbc9-23da98746665</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
