<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Today</name>
   <tag></tag>
   <elementGuidId>1805fa78-e83a-4036-ad71-fb80a1fe5327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ranges > ul > li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='myDIV1']/div[2]/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5fa35906-c248-46d2-97b0-f1ce8384c152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-range-key</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>29581e5e-f434-447f-adaf-20f7a661a9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Today</value>
      <webElementGuid>98b72340-a066-434c-ae5c-c94a0a1d004a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myDIV1&quot;)/div[@class=&quot;daterangepicker ltr show-ranges opensright&quot;]/div[@class=&quot;ranges&quot;]/ul[1]/li[1]</value>
      <webElementGuid>f5b70c4e-4b8b-4b67-81a6-44342b9b0b3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='myDIV1']/div[2]/div/ul/li</value>
      <webElementGuid>cf4e5732-b7d4-4983-9b10-6a4bc335bad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design &amp; Develop by Saneforce'])[1]/following::li[1]</value>
      <webElementGuid>0fa89f39-c714-4537-8efd-9ddc4c57d9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export To Excel'])[2]/following::li[1]</value>
      <webElementGuid>20c70f76-31ff-4339-a829-56aa92d02c0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yesterday'])[1]/preceding::li[1]</value>
      <webElementGuid>c9976917-1c23-41bb-a75b-5c8924cdd2c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last 7 Days'])[1]/preceding::li[2]</value>
      <webElementGuid>188c284f-f3e6-4907-88cb-7b95b6e10aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Today']/parent::*</value>
      <webElementGuid>1dde98a1-1754-428a-aa05-ef8edf95dfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li</value>
      <webElementGuid>7cc96a4d-da7a-40f3-baaf-d3a39e5d9d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Today' or . = 'Today')]</value>
      <webElementGuid>17c79a0b-3fa0-4708-aa29-2f5c34104003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
