<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leave</name>
   <tag></tag>
   <elementGuidId>40a7392c-19d1-4c02-9337-78ad10a87a9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='submenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>42118b6d-5347-418d-b9ed-60a257498c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Leave/UserReport</value>
      <webElementGuid>a02349ad-919d-4e04-9087-22a822a41ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>ae169537-eda3-4d51-89d2-972a03d5b12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>t-leave</value>
      <webElementGuid>2bded2b4-7cff-49f5-85b3-52c44ae810f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submenu</value>
      <webElementGuid>a6e0b116-0962-4377-9788-ed47991866bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Leave </value>
      <webElementGuid>eb8705a9-c85d-4db7-88b0-02a8f3bb8a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarApps&quot;)/ul[@class=&quot;nav nav-sm flex-column submenu_align&quot;]/li[@class=&quot;Employee_8 nav-item align-items-start&quot;]/a[@id=&quot;submenu&quot;]</value>
      <webElementGuid>80db91da-5f81-415f-88c4-9b7acae58633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='submenu']</value>
      <webElementGuid>169bd589-0650-42ff-b561-7b5179755e79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarApps']/ul/li/a</value>
      <webElementGuid>2746fcc7-afab-4eb2-aa81-87b489e87fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Leave')])[2]</value>
      <webElementGuid>67598984-b13a-43ce-ba2a-c19544222b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[2]/following::a[2]</value>
      <webElementGuid>f75280ec-3601-4e22-99be-e00ba76542cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[2]/following::a[2]</value>
      <webElementGuid>c04d9c49-7536-4b56-b424-16042fa36f8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Attendance Summary'])[1]/preceding::a[1]</value>
      <webElementGuid>0f089bce-86f4-4408-8bed-dbd2e58577c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift Mapping'])[2]/preceding::a[2]</value>
      <webElementGuid>5458f7e0-80af-43d9-b094-5a9d6b3b55fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Leave/UserReport')])[2]</value>
      <webElementGuid>ac574090-a1c5-4174-9313-5c4574530cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/ul/li/a</value>
      <webElementGuid>c67697fb-fac0-4c70-9d9b-f8abdba271e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Leave/UserReport' and @id = 'submenu' and (text() = ' Leave ' or . = ' Leave ')]</value>
      <webElementGuid>a5f81e2d-1f8f-4ec4-b054-29388519e381</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
