<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leave History</name>
   <tag></tag>
   <elementGuidId>99e08d8b-c47e-4ceb-b4b2-b9306d4e2a60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lh']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bf4380a6-18a3-4ae1-acca-88b042d706f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Leave/LeaveHistory</value>
      <webElementGuid>72361e73-539a-4dc8-ad35-c22e5d092796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link fw-5 py-2</value>
      <webElementGuid>4dc03617-55c7-4919-bdc3-db6a8c4eda07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lh</value>
      <webElementGuid>2b31b67b-db74-42ec-9ec9-76793bd666bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>adca3915-f0a7-45cc-86cd-4a9518fd7677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f14268aa-3c4f-4122-9cb5-2d405332fcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e05b02a0-9f62-4bd8-a29e-a3ef82cab84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>active_link2()</value>
      <webElementGuid>95e3448b-0cf5-4635-8eeb-e0c73c20ee92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave History</value>
      <webElementGuid>bbc514b9-c8b1-4f36-b74d-ed13cd33548e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lh&quot;)</value>
      <webElementGuid>cfa87925-9e59-4d5f-a178-9fc01ed9cddc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lh']</value>
      <webElementGuid>e1a65ae9-8c3d-4379-86ab-a1332bca3f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leave']/div/nav/div/ul/li[2]/a</value>
      <webElementGuid>42d20acc-72db-4fa7-9a4c-bb1d4c1fc172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Leave History')]</value>
      <webElementGuid>b153c9d4-4827-45d9-b6cc-0fbe3062d4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Form'])[1]/following::a[1]</value>
      <webElementGuid>c5b02862-e896-4249-8849-b473cb180bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift Mapping'])[3]/following::a[2]</value>
      <webElementGuid>a0bb5139-553d-4c8c-aa2b-813544fea380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Balance'])[1]/preceding::a[1]</value>
      <webElementGuid>9dab0a77-c841-462e-8120-d116521bf6fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Attendance'])[1]/preceding::a[2]</value>
      <webElementGuid>a6e732cb-610f-4f5c-9e4f-3f3f330348e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave History']/parent::*</value>
      <webElementGuid>2be52587-a056-462c-bbed-13ab5deba99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Leave/LeaveHistory')]</value>
      <webElementGuid>c27cb21e-e097-43c3-935d-3706adfbb1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li[2]/a</value>
      <webElementGuid>5f2edad5-f93c-486e-9630-b6263adb0fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Leave/LeaveHistory' and @id = 'lh' and @type = 'button' and (text() = 'Leave History' or . = 'Leave History')]</value>
      <webElementGuid>496eb95a-30ad-46b2-b630-fdf33fce6f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
