<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leave Form</name>
   <tag></tag>
   <elementGuidId>85a3bb05-5ee9-47d6-ada5-45dc452c9257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lf']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c67a13dc-6363-4506-bb85-95d9695bc4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Leave/applyleave</value>
      <webElementGuid>c63264c4-41f6-4fea-82f6-c54297b17b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link fw-5 py-2</value>
      <webElementGuid>ae602f67-6184-42ec-a919-5052946bc5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lf</value>
      <webElementGuid>d879ede3-f833-4a71-a9f3-9e9db71594e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09e3a39c-db80-4233-acf3-ca3ee59b12f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>a6e62e2f-33b5-43ea-8365-4713461b09a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>347bae25-1c19-4a24-a23f-1543315e1994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>active_link1()</value>
      <webElementGuid>5ae20165-87b7-4aa4-bfd6-55ea1e2456ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Leave Form</value>
      <webElementGuid>771d7b44-5b23-4eb7-bb62-be684d2840b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lf&quot;)</value>
      <webElementGuid>9e5f8c00-9964-437b-a6c0-e7dd60b08665</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lf']</value>
      <webElementGuid>d216e16a-6206-4aa0-a320-19b22fe11485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='leave']/div/nav/div/ul/li/a</value>
      <webElementGuid>6e27b35d-6583-4677-853a-0841a7eb20c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Leave Form')]</value>
      <webElementGuid>a5da4b60-eae4-4adb-a352-7913a8b079d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift Mapping'])[3]/following::a[1]</value>
      <webElementGuid>36e8f3c8-194b-498e-90b2-6a290997a9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary'])[1]/following::a[2]</value>
      <webElementGuid>1bdbc726-6839-453a-b8c4-0dee0cbfe3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave History'])[1]/preceding::a[1]</value>
      <webElementGuid>6575f551-5654-4426-a3e6-eb886a07b8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Balance'])[1]/preceding::a[2]</value>
      <webElementGuid>129a65fc-61f1-4840-a77d-b9af3b93c437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Leave Form']/parent::*</value>
      <webElementGuid>4187ad7c-a333-442a-92ec-975799a7c71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Leave/applyleave')])[2]</value>
      <webElementGuid>0e6a857d-15c1-413d-9998-053e4641f5d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li/a</value>
      <webElementGuid>ac2fccbd-ea5f-460e-9a1c-2c18e6834c16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Leave/applyleave' and @id = 'lf' and @type = 'button' and (text() = 'Leave Form' or . = 'Leave Form')]</value>
      <webElementGuid>769859e3-1cb0-44a9-b83a-59cedbb34312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
