<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_----Select----</name>
   <tag></tag>
   <elementGuidId>b2392ae3-d57a-47e7-a090-d7e878e3c8f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.filter-option-inner-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layout-wrapper']/div[15]/div/div/div/div/div/div[3]/form/div/div/div/div/div/button/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dd7496ba-9a80-4b63-bcf0-7efc9edece3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-option-inner-inner</value>
      <webElementGuid>471a6740-f89c-4bbd-a771-34a41feb96d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>----Select----</value>
      <webElementGuid>6beeaf11-ea73-429c-9292-19a523fdfb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;layout-wrapper&quot;)/div[@class=&quot;main-content&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;navbar-header-1&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-8 col-lg-8 col-xl-8 col-xxl-8  mb-4&quot;]/div[@class=&quot;leave_details card p-3 mb-3&quot;]/div[@class=&quot;card-body pb-0&quot;]/form[1]/div[@class=&quot;leave_Details_form&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl6&quot;]/div[@class=&quot;employee_name mb-3&quot;]/div[@class=&quot;dropdown bootstrap-select&quot;]/button[@class=&quot;btn dropdown-toggle bs-placeholder btn-light show&quot;]/div[@class=&quot;filter-option&quot;]/div[@class=&quot;filter-option-inner&quot;]/div[@class=&quot;filter-option-inner-inner&quot;]</value>
      <webElementGuid>4c20e1ea-239c-47ff-bbd2-ad4844ab1765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[15]/div/div/div/div/div/div[3]/form/div/div/div/div/div/button/div/div/div</value>
      <webElementGuid>e76ecfb3-58df-43cc-8ca0-8aa7eea8753e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[4]</value>
      <webElementGuid>e46a9b47-fc90-4607-87b6-3444744e082c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::div[4]</value>
      <webElementGuid>f8774982-d41b-462d-a6b7-2771d7828c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div/div/div</value>
      <webElementGuid>a4d8f5c3-57b5-4ad5-805f-92f605b65caf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '----Select----' or . = '----Select----')]</value>
      <webElementGuid>47d085ff-0f2e-4ffe-a419-38c2a11942f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
