<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i__bi bi-eye</name>
   <tag></tag>
   <elementGuidId>56af59fc-7aef-4f15-8704-6009b75c3926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.pay_view.pay_view_color.pe-1 > i.bi.bi-eye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='leavehistory']/tbody/tr/td[10]/a/span/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>98df3d12-f0e7-4378-871a-50b588a3f0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-eye</value>
      <webElementGuid>12277a5e-8e22-414e-8d35-c407b360bd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leavehistory&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[10]/a[1]/span[@class=&quot;pointer er&quot;]/span[@class=&quot;pay_view pay_view_color pe-1&quot;]/i[@class=&quot;bi bi-eye&quot;]</value>
      <webElementGuid>32c220e1-7d38-4824-add4-51e5a0b4d8b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='leavehistory']/tbody/tr/td[10]/a/span/span/i</value>
      <webElementGuid>55a28e65-bfc9-47f7-83e3-e1e21f968dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span/span/i</value>
      <webElementGuid>104d1c61-6aff-497a-978f-f40e63e0cc1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
