<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fromdate</name>
   <tag></tag>
   <elementGuidId>dd7878a3-393a-485f-b776-7e20efa1c65a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c8501af-0cb8-40d6-9187-8cc5bb0bcbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3933b84b-7038-45a8-b78f-e0fb259355f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control startDate</value>
      <webElementGuid>070a153b-4deb-4b28-996d-f26019a1d146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromdate</value>
      <webElementGuid>e9de45c3-0dda-4170-bf7b-848ca5bc3bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromdate&quot;)</value>
      <webElementGuid>234f4410-7c78-4c91-b06f-ba289dedf0cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fromdate']</value>
      <webElementGuid>3d4816ba-2417-48e3-b2b5-d187441fa036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[15]/div/div/div/div/div/div[3]/form/div/div[2]/div/div/input</value>
      <webElementGuid>937ebda6-1b4c-44fb-86d3-41d44ecade4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div/div/input</value>
      <webElementGuid>a21f35ac-9034-4e84-9665-e8f0f6362696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fromdate']</value>
      <webElementGuid>d834410e-10bb-41f0-b12f-8002b1ddbbab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
