<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_----Select----paid leaveCasual Leave_f545c5</name>
   <tag></tag>
   <elementGuidId>d8dc81e3-454c-434d-b0f8-4c9f0399fc32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LevtY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LevtY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0178482a-a931-421e-bd9b-28c0d785d6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LevtY</value>
      <webElementGuid>2a94a897-7a11-4ec7-890f-5137d69a76e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LevtY</value>
      <webElementGuid>5e84ca0c-1885-45cd-a1d8-4766c62b58d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>603b808b-f692-4946-90b2-7bac0f51151b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>availbal();</value>
      <webElementGuid>7e551f53-7ef2-43c9-a784-10afbea9bf59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>----Select----paid leaveCasual LeaveEARNED LEAVEMEDICAL LEAVECOMPENSATORY OFFLEAVE RESET YEARLY CARRY FORWARD ACCURAL YEARLY OCTOBER 1LEAVE RESET WEEKLY CARRY FORWARD 1LEAVE ACCURAL MONTHLY RESET MONTHLY CF UNITS 1Automation Leave type</value>
      <webElementGuid>48c10ae8-eb45-4f4b-af2a-3d98b51c977f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LevtY&quot;)</value>
      <webElementGuid>b49a7b13-6ea6-4879-9710-863c9edee495</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LevtY']</value>
      <webElementGuid>b9bb9c89-41cd-48fb-acd8-8f55c5b09b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[15]/div/div/div/div/div/div[3]/form/div/div/div[2]/div/div/select</value>
      <webElementGuid>58aff0d3-4dba-485e-8b1d-2e291ce8e6b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::select[1]</value>
      <webElementGuid>0a858c01-b589-42ef-a16d-0e505d3dc4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='----Select----'])[4]/preceding::select[1]</value>
      <webElementGuid>85c10259-435b-41aa-bd17-be4d2a12aa1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='----Select----'])[5]/preceding::select[1]</value>
      <webElementGuid>434e483f-cfbd-48f8-82f4-54858e8e36d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>a60fb321-76a2-4eee-b5ab-5f25c4439ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'LevtY' and @id = 'LevtY' and (text() = '----Select----paid leaveCasual LeaveEARNED LEAVEMEDICAL LEAVECOMPENSATORY OFFLEAVE RESET YEARLY CARRY FORWARD ACCURAL YEARLY OCTOBER 1LEAVE RESET WEEKLY CARRY FORWARD 1LEAVE ACCURAL MONTHLY RESET MONTHLY CF UNITS 1Automation Leave type' or . = '----Select----paid leaveCasual LeaveEARNED LEAVEMEDICAL LEAVECOMPENSATORY OFFLEAVE RESET YEARLY CARRY FORWARD ACCURAL YEARLY OCTOBER 1LEAVE RESET WEEKLY CARRY FORWARD 1LEAVE ACCURAL MONTHLY RESET MONTHLY CF UNITS 1Automation Leave type')]</value>
      <webElementGuid>a5e1c87e-4f1d-470d-9afe-6d85f6f97425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
