<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1 Half2 Half</name>
   <tag></tag>
   <elementGuidId>420e130e-99c9-4943-a87f-3c9d0c96dd83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hdisp_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='hdisp_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>88d9cc65-f912-4d89-8222-c85ba5403c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select select_day_type box_disabled</value>
      <webElementGuid>2cdf6bfa-c2c1-4164-933f-1ae45d4d5839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hdisp</value>
      <webElementGuid>e121aeb2-aba7-4450-8d4f-3b6883468a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Default select example</value>
      <webElementGuid>f042352f-439c-4978-9df1-67904bed85db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hdisp_1</value>
      <webElementGuid>0449afc3-8831-4c32-a318-5b0a51cb3dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Half2 Half</value>
      <webElementGuid>8d8a69b9-1079-4169-bce3-bb710c0614b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hdisp_1&quot;)</value>
      <webElementGuid>535bd87f-70fa-4a2e-a0da-9df6e940b817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='hdisp_1']</value>
      <webElementGuid>c773dd2c-7025-4261-a981-2ccc10d8ed7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbldate']/div/div[3]/div/select</value>
      <webElementGuid>104e8f8e-f830-4701-acf8-e2498293a535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat 23-Mar-2024'])[1]/following::select[2]</value>
      <webElementGuid>f774f0b4-fe54-4c73-af9f-87cc622f907e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Date'])[1]/following::select[2]</value>
      <webElementGuid>6604140b-c949-4ffa-af01-1e65861cca02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>1ffe78a1-174a-4d78-98f5-54ff9f6718f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>5d289f5a-e971-4136-9079-ecc6943921bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'hdisp' and @id = 'hdisp_1' and (text() = '1 Half2 Half' or . = '1 Half2 Half')]</value>
      <webElementGuid>5d251f58-442e-4f1f-b10e-b8343782b800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
