<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_----Select----Mounika m  (CBS0679)</name>
   <tag></tag>
   <elementGuidId>db1a5e14-9cc6-4267-b731-d09dfa2394ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='emp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9d1bc731-b8ea-4c32-854c-2c3bd17306f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emp</value>
      <webElementGuid>8c8f63c3-d796-465c-897d-d12cb707080a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emp</value>
      <webElementGuid>aa8c63ee-6210-4515-a296-2065167d7f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-live-search</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7c45bf27-ffca-4eb7-9885-0a325ee15d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>GetLeaveType(this.value); getmail(this.value)</value>
      <webElementGuid>5ad7ab43-f97d-478d-a2b1-bc73e1d528ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>----Select----Mounika m  (CBS0679)</value>
      <webElementGuid>c509967c-5a37-455a-bc56-ca9f26acd734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emp&quot;)</value>
      <webElementGuid>40054a96-b8fb-461b-9e92-b1e49bb15e45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='emp']</value>
      <webElementGuid>f0c53613-9f46-4d33-854f-dbbec31d688f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[15]/div/div/div/div/div/div[3]/form/div/div/div/div/div/select</value>
      <webElementGuid>af3fd387-8359-40dc-85fd-067154152d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>ffb3883a-e431-4c3c-a156-b5643b9cc18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='----Select----'])[2]/preceding::select[1]</value>
      <webElementGuid>1cc6d8da-40f5-4b27-9055-3ac88bfa7158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='----Select----'])[3]/preceding::select[1]</value>
      <webElementGuid>d3ba7fe0-63ed-48e3-a319-4069181a2a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/select</value>
      <webElementGuid>29f42b54-d59b-4a99-8bca-d8a8ede11d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'emp' and @id = 'emp' and (text() = '----Select----Mounika m  (CBS0679)' or . = '----Select----Mounika m  (CBS0679)')]</value>
      <webElementGuid>dc7e7b45-81e4-4902-9ddc-d4120bef1608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
