<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Full DayHalf Day</name>
   <tag></tag>
   <elementGuidId>2ad5d097-af5d-4eb0-a053-b4d41747fa37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hful_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='hful_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9712b11-840a-4fc5-89b4-c68027cd70aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select select_day_type dful dfulnodis</value>
      <webElementGuid>74f10b1a-5a9a-47b6-ae56-15ad7d187939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hful</value>
      <webElementGuid>6410cbd1-c7aa-43de-8416-64ae870b64a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hful_1</value>
      <webElementGuid>f7c003f5-3358-49a3-b2be-3330f3802f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typ</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>30287e21-d65a-4d07-b060-8a90f409bf0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>fnlevty(this,1)</value>
      <webElementGuid>ce690c54-ed72-4025-9d61-4fa036add0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Default select example</value>
      <webElementGuid>5f177d4c-64f3-4c96-bd76-661eb84e6836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full DayHalf Day</value>
      <webElementGuid>4f00be85-4fc0-4185-8f9a-df3cfd00d40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hful_1&quot;)</value>
      <webElementGuid>3bc50cf6-86c7-4263-a5b8-b64a81cb9943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='hful_1']</value>
      <webElementGuid>2d753c6c-71b6-48d9-9264-f96eb705b0d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tbldate']/div/div[2]/div/select</value>
      <webElementGuid>22740d13-462c-45e8-8d2c-76f29a504b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sat 23-Mar-2024'])[1]/following::select[1]</value>
      <webElementGuid>dc53757a-410a-477b-81ee-b998aec0549e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave Date'])[1]/following::select[1]</value>
      <webElementGuid>956881d0-241e-449b-8a1e-8596212621ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[2]</value>
      <webElementGuid>1ca8eaea-b1d9-4815-ad8b-e8bb4ce73efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>619bb0a1-9e29-42b6-acbc-b39d000d9782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'hful' and @id = 'hful_1' and (text() = 'Full DayHalf Day' or . = 'Full DayHalf Day')]</value>
      <webElementGuid>2a540fd4-394e-4465-9901-1f84ecc738c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
