<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mounika m  (CBS0679)</name>
   <tag></tag>
   <elementGuidId>1ff37a22-b0e6-4b2f-87fa-c44fea858faa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bs-select-3-1 > span.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='bs-select-3-1']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7b64f590-e14e-4eb8-9229-094403575385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e95b78e-487b-4530-b869-cdf760b57f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mounika m  (CBS0679)</value>
      <webElementGuid>446b6df7-1f53-417b-94c8-33483349e986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bs-select-3-1&quot;)/span[@class=&quot;text&quot;]</value>
      <webElementGuid>6e4610c9-3805-47f3-ade7-10d3ba612882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='bs-select-3-1']/span</value>
      <webElementGuid>32384f13-a4d0-452c-8253-882fb48b7c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='----Select----'])[3]/following::span[1]</value>
      <webElementGuid>1cf22409-479d-4eba-8050-8338f5678a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='----Select----'])[2]/following::span[2]</value>
      <webElementGuid>f2f4518d-25c5-4cb5-978f-a3bb20287b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[1]</value>
      <webElementGuid>82af767d-4b52-4678-9c9f-8676b0bbd02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>195a9518-fadf-461d-8d0a-0280beb07e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Mounika m  (CBS0679)' or . = 'Mounika m  (CBS0679)')]</value>
      <webElementGuid>7ebcfe49-b49d-4c65-af51-76970a5f91ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
