<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__Reason</name>
   <tag></tag>
   <elementGuidId>47ef140f-55e4-4775-8b90-e14600742344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Reason</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Reason']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>88a99238-26ca-47f8-905e-526f16dc1e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9b875362-e0cd-4b78-a0e6-275d4aaf981d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Reason</value>
      <webElementGuid>8dc60786-33f0-43fb-9a0d-833893e63285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Reason</value>
      <webElementGuid>3a935dd6-c13d-4ddf-8b25-c536396e10da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Reason&quot;)</value>
      <webElementGuid>7b6143d5-a6e3-4334-8c6c-21c6bc5ae53f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Reason']</value>
      <webElementGuid>0e8fe55c-0cd2-491c-a186-a9524681d503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layout-wrapper']/div[15]/div/div/div/div/div/div[3]/div/div[3]/div[2]/textarea</value>
      <webElementGuid>f6f3f4fd-b476-4ac9-8a74-f8effdd4241f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>1a8d58ac-009d-4846-a566-9dd074c5914b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'Reason' and @id = 'Reason']</value>
      <webElementGuid>60b98313-b0f5-423c-8dd8-7988f8eaff2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
