<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Scroll to Page down</name>
   <tag></tag>
   <elementGuidId>dc64c5b9-9bfd-49c7-a288-40d8f95cc99c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#datatable_info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='datatable_info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>85e90c97-9fa3-4598-a075-1416e5adbe33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_info</value>
      <webElementGuid>d551d948-492e-4842-9007-378ba9e08458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datatable_info</value>
      <webElementGuid>d95a5826-c248-413e-9e66-e364d22e5c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>d538786e-73de-452d-b617-cd044914fbdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>154c8eed-56e4-443f-b8ad-5b7c371cc39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showing 1 to 8 of 8 entries</value>
      <webElementGuid>9b2d560b-dd2b-4eda-b35a-9703688e6c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datatable_info&quot;)</value>
      <webElementGuid>f2a06891-453e-4ab7-8b25-ddc00384c860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='datatable_info']</value>
      <webElementGuid>284a68ee-570a-4596-a5ae-94f1fdf1dd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='datatable_wrapper']/div[4]</value>
      <webElementGuid>c023dadc-18ee-41d4-9123-f897f28e2661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yashik'])[8]/following::div[1]</value>
      <webElementGuid>739066fe-39d6-4def-98fc-fd888c95096d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yashik'])[7]/following::div[1]</value>
      <webElementGuid>4b2e2f0c-66dc-4fff-a861-d70449f0e860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design &amp; Develop by Saneforce'])[1]/preceding::div[3]</value>
      <webElementGuid>68c145d7-fbe6-4773-b36b-869864891180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Showing 1 to 8 of 8 entries']/parent::*</value>
      <webElementGuid>302771f2-c79a-4a30-a1e7-2d49a39909e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div[3]/div/div[4]</value>
      <webElementGuid>4fc8028f-b5c8-493e-94ec-d5a078363c62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'datatable_info' and (text() = 'Showing 1 to 8 of 8 entries' or . = 'Showing 1 to 8 of 8 entries')]</value>
      <webElementGuid>1e09bc86-59bf-4c1a-9e5e-660163f095e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
