<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Leave</name>
   <tag></tag>
   <elementGuidId>7a51f65e-9d03-4efc-8d91-0bf4a8d9b64a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submenu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='submenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d2426d04-d6d5-447d-a207-0e284cb183a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Leave/UserReport</value>
      <webElementGuid>770203f5-fd22-41d9-81c5-9556f03c2aeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>b59010fd-7571-4bd4-b36a-65020e06e2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>t-leave</value>
      <webElementGuid>a71fc7ea-1d3d-4d48-89cd-7b5af2a8f42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submenu</value>
      <webElementGuid>f7ad9dce-72a3-4528-8812-9a1a33cbeec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Leave </value>
      <webElementGuid>f9ae60e9-8803-4f3a-8f67-1311c70621c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebarApps&quot;)/ul[@class=&quot;nav nav-sm flex-column submenu_align&quot;]/li[@class=&quot;Employee_8 nav-item align-items-start&quot;]/a[@id=&quot;submenu&quot;]</value>
      <webElementGuid>c3127b3c-9e61-425b-9e36-f8e1a04a45b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='submenu']</value>
      <webElementGuid>8f651af9-f223-4d27-b2b0-7f81ea80daa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sidebarApps']/ul/li/a</value>
      <webElementGuid>0da85c6c-b9a5-4d90-8a39-3de2e8426c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Leave')])[2]</value>
      <webElementGuid>e21f2462-4356-4196-b9f7-ebe8a8d258f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[2]/following::a[2]</value>
      <webElementGuid>f2255412-2068-4432-a31c-03184aa77b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity'])[2]/following::a[2]</value>
      <webElementGuid>6951f013-9c94-4b58-8d72-c05178ca8491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Attendance Summary'])[1]/preceding::a[1]</value>
      <webElementGuid>279ab7ea-a068-4a02-af7b-0cd46aac082a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift Mapping'])[2]/preceding::a[2]</value>
      <webElementGuid>c7ce79ca-f424-4689-ba68-f1cb41d2e896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/Leave/UserReport')])[2]</value>
      <webElementGuid>672489e8-32a7-40c0-aaad-8f1a3cddadcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/ul/li/a</value>
      <webElementGuid>c7604608-303a-42c5-9a28-217b8a35caaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Leave/UserReport' and @id = 'submenu' and (text() = ' Leave ' or . = ' Leave ')]</value>
      <webElementGuid>e147d6c6-cc56-4fce-b601-e93f6de32d94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
