<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkin button AR</name>
   <tag></tag>
   <elementGuidId>c33f970d-b8bb-49bf-bb34-d50a69a57fc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-outline-success.btn-sm.me-auto.chkin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divCheckinOut']/div/div/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ba60d673-2c1e-4873-8685-8fffa5a6b8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-success btn-sm me-auto chkin</value>
      <webElementGuid>122a2b8a-20f7-405b-a1ab-c3b156214633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Check-In</value>
      <webElementGuid>61857015-2ebe-4f1a-a34d-6c42e37bfedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divCheckinOut&quot;)/div[@class=&quot;dropdown dropdown_align d-none d-sm-block&quot;]/div[@class=&quot;d-grid gap-2&quot;]/div[@class=&quot;dropdown-menu dropdown_align p-3 chk1 show&quot;]/div[@class=&quot;text-end mt-3&quot;]/button[@class=&quot;btn btn-outline-success btn-sm me-auto chkin&quot;]</value>
      <webElementGuid>36558dc9-d354-4c41-8c38-a180fb620383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCheckinOut']/div/div/div/div/button</value>
      <webElementGuid>caef6e12-ef83-4f8c-b723-ca775cdd5110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::button[1]</value>
      <webElementGuid>76f6cde7-aee8-47ac-981b-fc446a274f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check-In'])[1]/following::button[1]</value>
      <webElementGuid>5b6e596f-25dd-4075-99cf-06e698e849d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check-Out'])[1]/preceding::button[1]</value>
      <webElementGuid>477d97d4-f987-4db9-8bf9-f8458ac37487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[2]/preceding::button[2]</value>
      <webElementGuid>d2414286-3d8c-4f5b-886c-8169114d1d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/div/div/div/div/div[2]/div/div/div/div/button</value>
      <webElementGuid>24a0727b-6020-4453-958c-8c8eadd530cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Check-In' or . = 'Check-In')]</value>
      <webElementGuid>f306ed30-897a-4064-a8f5-aabe998a6301</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
