<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkout Remarks</name>
   <tag></tag>
   <elementGuidId>bb8781af-d89e-4cb7-869c-f501985cd65a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notenameout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notenameout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5199e4ac-7f02-43b3-be86-d5a711b037cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cdc56b77-1727-4054-ae96-8be378212bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6b9cd129-004c-4ba7-9b06-fbd93a3a1d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notenameout</value>
      <webElementGuid>2fee75bf-c0e8-465d-9da3-ad9985215599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Remarks</value>
      <webElementGuid>c9899ef6-9b0b-4c14-bb76-1a4485962871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notenameout&quot;)</value>
      <webElementGuid>d57cd925-a50a-4631-a36b-cecd1cddb631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notenameout']</value>
      <webElementGuid>d9c3ba65-efe6-45cc-b624-0aad287a1f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCheckinOut']/div[2]/input</value>
      <webElementGuid>cb2c4c30-c20b-45ea-ab8f-6d749c7d0ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>d41c4ad7-4014-4e7f-aea5-e5db816714c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'notenameout' and @placeholder = 'Enter Remarks']</value>
      <webElementGuid>f89e7d0f-bdbc-477a-971e-f869c7851113</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
