<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkin button BR</name>
   <tag></tag>
   <elementGuidId>8ef45378-f09f-4d6a-8523-875cf5530da1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropdownMenuLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dropdownMenuLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c55d0a46-1346-4e1c-bc3e-940a18064f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm check_out_btn pe-4 chkinAM bg_g_color w-color show</value>
      <webElementGuid>a6c329a6-f80a-4bf5-aa7c-6ba48afbac91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdownMenuLink</value>
      <webElementGuid>5cfb312c-d061-4518-a890-6664fb526914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>9b0da4fc-45f4-4fd8-a959-a77f2c22c3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9c0bd93c-2ba1-4433-b198-a4f49db0bf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Check-In
                                                                        00:00:00
                                                                    </value>
      <webElementGuid>d136f0d3-6c92-4a1f-9fd2-899262989f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divCheckinOut&quot;)/div[@class=&quot;dropdown dropdown_align d-none d-sm-block&quot;]/div[@class=&quot;d-grid gap-2&quot;]/button[@id=&quot;dropdownMenuLink&quot;]</value>
      <webElementGuid>3d5ee8ac-087d-4b33-8ac9-ec4af32e7834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dropdownMenuLink']</value>
      <webElementGuid>95653778-082b-4dbc-b90b-e3add4ad68e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCheckinOut']/div/div/button</value>
      <webElementGuid>07ec5557-8317-4110-a8b8-2814bcf362dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Date and Time'])[1]/following::button[1]</value>
      <webElementGuid>d1026af3-26f2-40ed-af1d-51c721cf94c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remote Login'])[1]/following::button[1]</value>
      <webElementGuid>84d01014-5c4b-42de-8e62-a663f73cc30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/preceding::button[1]</value>
      <webElementGuid>ad862cec-ca02-4195-bfec-fe12b3c945f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div/button</value>
      <webElementGuid>fba7bdf8-0b53-4969-ac52-a1c1eebf4635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'dropdownMenuLink' and (text() = '
                                                                        Check-In
                                                                        00:00:00
                                                                    ' or . = '
                                                                        Check-In
                                                                        00:00:00
                                                                    ')]</value>
      <webElementGuid>00214802-e56d-4a6f-86f1-675266b9bd5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
