<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Checkin remark</name>
   <tag></tag>
   <elementGuidId>cd5f15b3-421a-42bc-ac39-816073088594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#notenamein</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='notenamein']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20e2a87f-6fe5-44b8-81d6-8b8fdc3e6b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>142fb29b-6a7c-4908-a470-997df0ebb887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>01fa5217-dc8a-4b74-90fa-b23cbfa05eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>notenamein</value>
      <webElementGuid>7fc89a80-b2ae-4dbb-9064-45734a923920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Remarks</value>
      <webElementGuid>c772fd62-76e7-456a-8045-8dcea65e526b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;notenamein&quot;)</value>
      <webElementGuid>6e934b7f-60b6-4699-83e0-2249f41d8ad1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='notenamein']</value>
      <webElementGuid>8cac096c-3737-47f2-8645-04259ffc7068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCheckinOut']/div/div/div/input</value>
      <webElementGuid>5c712e89-1a6a-4cee-a9e7-97ab619c1b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>b8f86d3b-958d-4a5d-bc20-782beeab301c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'notenamein' and @placeholder = 'Enter Remarks']</value>
      <webElementGuid>f17237c6-472b-4b4d-9c77-1c644659a6c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
