<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OD date selection</name>
   <tag></tag>
   <elementGuidId>3cfb87fc-12d9-4cba-a7b8-996dc21c5bab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ODdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ODdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc5e6ace-b22c-47f9-bb26-83ada866333d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a279b8da-c20d-4105-9115-807b0a3de206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control startDate</value>
      <webElementGuid>4e739d99-987f-4f0a-bbc4-cb94b3d660dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ODdate</value>
      <webElementGuid>23290520-679e-4e52-a9e8-04e838e0432e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ODChkinChkoutenabledisable()</value>
      <webElementGuid>ef9ca7e6-0f14-4f41-bf33-b6154b9889a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ODdate&quot;)</value>
      <webElementGuid>fe0a2228-2307-4017-8329-294378ae6232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ODdate']</value>
      <webElementGuid>0aaf302a-6739-4b2e-8126-2fb23936c062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idOnDuty']/div/div[3]/div/div/div/input</value>
      <webElementGuid>fc694938-e8aa-44c4-a9a3-a4f84fd540d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>5a4addf2-762a-41f0-94c4-b21e2dff5804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ODdate']</value>
      <webElementGuid>be868262-1058-4726-9317-51e57117f2e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
