<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OD Remarks</name>
   <tag></tag>
   <elementGuidId>3fb28ada-2e5d-4e3b-adb7-77d85b258a79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ODRemarks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ODRemarks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dfe9953d-4b83-4fc8-bf78-384c517a43aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2aec93d4-1331-4d7a-9f81-c6305627c38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ODRemarks</value>
      <webElementGuid>857870f7-c134-4568-831b-fc2675b304f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ODRemarks&quot;)</value>
      <webElementGuid>d4dfe43d-394e-4fb3-b7d3-eaca48be4921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ODRemarks']</value>
      <webElementGuid>b85308fa-51d1-42d5-86e8-bf46efb29242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idODRemarks']/textarea</value>
      <webElementGuid>3fe826b8-2686-4bf0-ac62-93c467dc8515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/div[3]/div[3]/div[6]/div/textarea</value>
      <webElementGuid>1dc1df5c-7c56-4981-8506-ee004efec9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ODRemarks']</value>
      <webElementGuid>e5ad56c8-161b-4d12-9261-2fbc74305a5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
