<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>On Duty button</name>
   <tag></tag>
   <elementGuidId>57f46ee4-1ae0-4d49-b756-06d6cf2b6746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#divOnDuty > button.btn.btn-primary.fw-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divOnDuty']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>adcae7a4-86b9-4224-aa0f-15f68c7877d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary fw-5</value>
      <webElementGuid>ba5c2456-b1a3-4e9b-8929-898309773845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>9c181f6c-c5d9-4a60-b4d3-58e4ebe4981d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#onduty</value>
      <webElementGuid>f75e3b62-9fc9-417a-8079-3ea3467befbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>On Duty</value>
      <webElementGuid>5277867a-c505-4ece-b97d-036f6e7761d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divOnDuty&quot;)/button[@class=&quot;btn btn-primary fw-5&quot;]</value>
      <webElementGuid>742d5975-eb7c-40e2-8b49-4565b1b70b2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divOnDuty']/button</value>
      <webElementGuid>d2d11cf8-156b-4baa-af9c-9968e017a90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Work From Home'])[1]/following::button[1]</value>
      <webElementGuid>82febba7-4aab-4acf-bc50-fac23a00fd12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check-out'])[1]/following::button[2]</value>
      <webElementGuid>68f5e29f-86ef-46db-a713-9ff3a87067a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift Details'])[1]/preceding::button[1]</value>
      <webElementGuid>9c222266-6145-4954-a9db-a6948b924f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave balance'])[1]/preceding::button[1]</value>
      <webElementGuid>1725fba9-5a05-4db4-a848-bb1fabc5f1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='On Duty']/parent::*</value>
      <webElementGuid>caab38cd-4b7d-42a3-8e6f-2b0d3210bfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[4]/button</value>
      <webElementGuid>16b1839b-9f99-4647-8d72-82f32cc28d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'On Duty' or . = 'On Duty')]</value>
      <webElementGuid>c7d6d415-144c-4cbf-90be-115b949fc624</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
