<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WFH date selection</name>
   <tag></tag>
   <elementGuidId>89f95baf-913c-4769-b5e8-a88cae9786cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Wfhdate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Wfhdate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3bbe6bfd-6574-4e7a-a4e6-4882034c6148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a909b787-789a-42ac-b216-0a1f8eb72ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control startDate</value>
      <webElementGuid>3ace3bae-ecf6-4dcf-bdd5-f6f18a8c04e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Wfhdate</value>
      <webElementGuid>f5f5d1a3-e8f5-46b1-a3d9-0ce24deb39a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ChkinChkoutenabledisable()</value>
      <webElementGuid>44797b91-7bc5-4f98-b9df-7df801ceecb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Wfhdate&quot;)</value>
      <webElementGuid>c3cf937f-41e8-4da9-beb0-cd82d64e95d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Wfhdate']</value>
      <webElementGuid>44a67618-85e2-4867-91d2-ecbe0cad733f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idworkfromhome']/div/div[3]/div/div/div/input</value>
      <webElementGuid>842e3422-b06f-4f04-b56a-1f4e15e0de58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>22d2e9d2-1b9f-44c6-8ac2-43167df4c18e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Wfhdate']</value>
      <webElementGuid>fe61029b-12cc-4e21-bd81-21246be2a3ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
