<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WFH Remark</name>
   <tag></tag>
   <elementGuidId>42bfbaae-65f0-478c-b4f7-10a84c70bef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WRemarks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='WRemarks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>715b8403-dadc-48fc-8c88-d4d2dfd5a6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>77e3684b-a1be-47b8-b08f-9a8a795f7a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WRemarks</value>
      <webElementGuid>4b65af50-6f03-4a94-a313-0a59a65672c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WRemarks&quot;)</value>
      <webElementGuid>2e3b8f87-7766-4524-addb-919602f8bad8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='WRemarks']</value>
      <webElementGuid>90158c0c-ba3c-4a57-841a-f0744de5056c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idRemarks']/textarea</value>
      <webElementGuid>e47711cb-5552-4f69-ac29-9d8c8e1fc2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/textarea</value>
      <webElementGuid>5e0455cf-ad18-4147-aefc-12c053f8a2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'WRemarks']</value>
      <webElementGuid>e8738c07-9761-4dc5-a452-eb3b5b10bcd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
