<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Work From Home Button</name>
   <tag></tag>
   <elementGuidId>76f45063-3545-4a49-9e00-5fa39bc57854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.fw-5.px-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='divwrokfromhome']/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32224eca-94fc-4fc3-8346-48547adc2c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary fw-5 px-2</value>
      <webElementGuid>cc18f787-5dc5-4b53-837b-b3437fcdb5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>89bfb1a0-938e-47b7-9cf2-671f6b3acd55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#wfh</value>
      <webElementGuid>37baeaec-89c6-49e3-9373-c0e02f8c1d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Work From Home</value>
      <webElementGuid>0ab84381-30a0-4776-8faa-255d73e38975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divwrokfromhome&quot;)/div[@class=&quot;d-grid gap-2&quot;]/button[@class=&quot;btn btn-primary fw-5 px-2&quot;]</value>
      <webElementGuid>bb9306e9-6ee9-47be-992b-1b923213b3ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divwrokfromhome']/div/button</value>
      <webElementGuid>a5832580-709b-4d98-adf6-4dde152fc7e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check-out'])[1]/following::button[1]</value>
      <webElementGuid>f40f012f-f277-4a2e-9360-5159992a9d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[3]/following::button[2]</value>
      <webElementGuid>039c1d2f-5446-4a70-81d0-6d761c525cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Duty'])[1]/preceding::button[1]</value>
      <webElementGuid>33ed57fb-a82d-4cfe-b9f4-c2425b84baba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shift Details'])[1]/preceding::button[2]</value>
      <webElementGuid>5e5494c7-6d87-42e9-a383-c6ac8de87554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Work From Home']/parent::*</value>
      <webElementGuid>4c990579-b98f-41b6-9f7f-5120a2fe7eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]/div/div/div/div/div/div[3]/div/button</value>
      <webElementGuid>a1ccf03d-cc2a-401d-a197-0b7c0b2b991d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Work From Home' or . = 'Work From Home')]</value>
      <webElementGuid>5b1201df-60fe-4a84-9a00-9ef9df6f4ce8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
