<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Forgot Password or Username - link</name>
   <tag></tag>
   <elementGuidId>6e149f76-112d-4420-b623-c46c57333971</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='top']/form/div[2]/div/div/div/div/div[2]/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.text-forgot-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>99d3a339-bcfe-4b70-b6f6-b0274bf4cb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Home/RecoveryScreen</value>
      <webElementGuid>980aabc6-ec96-4faf-bde7-3b7cc9bdb28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-forgot-password</value>
      <webElementGuid>ce672eb4-5213-48ee-82d6-cc50bbf090e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forgot Password or Username?</value>
      <webElementGuid>b6027445-5785-4124-86d5-ca0b391b7736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/form[1]/div[@class=&quot;login-sef&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row login-box&quot;]/div[@class=&quot;col-lg-7 col-md-12 bg-color-16 align-self-center&quot;]/div[@class=&quot;form-section&quot;]/div[@class=&quot;login-inner-form&quot;]/div[@class=&quot;form-group&quot;]/a[@class=&quot;text-forgot-password&quot;]</value>
      <webElementGuid>ea969b2d-25cb-4107-a30d-a88aa748f945</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top']/form/div[2]/div/div/div/div/div[2]/div[3]/a</value>
      <webElementGuid>5d7d6d56-b612-4b65-b861-b0cf79ace92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot Password or Username?')]</value>
      <webElementGuid>207acdbd-3a48-4192-bcfa-33fb4c69ba57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to access 2GrowHR'])[1]/following::a[1]</value>
      <webElementGuid>3fef8dd1-190c-4873-8c61-30128b79e9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN'])[1]/preceding::a[1]</value>
      <webElementGuid>66169c5c-1ba8-4b49-b405-806451f4cba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SANeFORCE'])[1]/preceding::a[1]</value>
      <webElementGuid>d0cb1198-0e41-49ec-bcfa-8023cd9bb494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Forgot Password or Username?']/parent::*</value>
      <webElementGuid>b1335ea3-b177-4fbb-8e36-95b3cb0a749a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Home/RecoveryScreen')]</value>
      <webElementGuid>9050ce4b-3f07-4824-9edb-ae81148db464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>d18ea36c-11e1-4045-a8e6-af79ff9484ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Home/RecoveryScreen' and (text() = 'Forgot Password or Username?' or . = 'Forgot Password or Username?')]</value>
      <webElementGuid>045c352d-0e80-4960-8551-367761f1333f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
