<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login Button</name>
   <tag></tag>
   <elementGuidId>20611dcb-e5af-449d-8e4f-185c52f1c7de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-md.btn-theme.btn-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3849c4cf-167e-4bfb-ac65-4b6d91722568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>45f93330-8e88-47cf-98fe-be9186745451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-md btn-theme btn-block</value>
      <webElementGuid>1810b673-74ef-43d3-8857-a4d15f4e2138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>process()</value>
      <webElementGuid>41f30ab4-e86c-497f-80f6-bef5e7fd49b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>2f7c7df8-8c0e-4eeb-89e5-92eb9bec5ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top&quot;)/form[1]/div[@class=&quot;login-sef&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row login-box&quot;]/div[@class=&quot;col-lg-7 col-md-12 bg-color-16 align-self-center&quot;]/div[@class=&quot;form-section&quot;]/div[@class=&quot;login-inner-form&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn-md btn-theme btn-block&quot;]</value>
      <webElementGuid>2f52af44-dda3-4661-bf1e-d062d4427e52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>989da91a-a20a-48ab-9586-b21be8e8affd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top']/form/div[2]/div/div/div/div/div[2]/div[4]/button</value>
      <webElementGuid>5115c902-f75d-4d51-a707-3d5f4f990de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password or Username?'])[1]/following::button[1]</value>
      <webElementGuid>43870d52-3674-4b4d-ba99-75d33dc7d344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in to access 2GrowHR'])[1]/following::button[1]</value>
      <webElementGuid>031ccfe5-1890-4547-a66b-da774cea8e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SANeFORCE'])[1]/preceding::button[1]</value>
      <webElementGuid>db156016-0f19-4e3d-89e9-c79aebdf6922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAN Pharma SFA'])[1]/preceding::button[1]</value>
      <webElementGuid>e2c0940c-5688-4782-8d31-847cb80eecd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>484ae815-b974-4499-bef5-3f01833cc286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>a79cbd5a-a2e0-4bbf-aed3-37f48bd7557a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>d51a42a2-40c4-4661-b8ff-e6ccf810e09e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
