<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password - view icon</name>
   <tag></tag>
   <elementGuidId>7d3631a7-0595-4fbf-8845-925753cfd994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='password_icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4ae61503-a6ed-41a3-b303-a1683630c4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Assests/NewDesign/assets/images/newimg/signup/eye.svg</value>
      <webElementGuid>2a6c2c9c-ee53-4f44-a93d-558852ce39bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fuild password</value>
      <webElementGuid>56da0aa7-d929-4f51-9ce1-9485167f88b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_icon</value>
      <webElementGuid>1840b1cc-7b86-422c-b507-028f2a164cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>user</value>
      <webElementGuid>60a098af-9dc0-492c-99df-96cdcd96c31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>pass_show()</value>
      <webElementGuid>2f42a846-7353-4674-861b-a0c2ad21315f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_icon&quot;)</value>
      <webElementGuid>3a1b680f-76ad-4247-8a09-d75ab00bb374</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='password_icon']</value>
      <webElementGuid>22791d34-2aca-493d-b178-2a9f8efae765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='top']/form/div[2]/div/div/div/div/div[2]/div[2]/img</value>
      <webElementGuid>616c7a5c-66c0-452c-b5c1-32b10fdbfd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='user'])[2]</value>
      <webElementGuid>68a38d45-572c-4cc6-a2bd-617dfa0e4b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>1f844a1d-5901-4044-8624-ae2015255d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Assests/NewDesign/assets/images/newimg/signup/eye.svg' and @id = 'password_icon' and @alt = 'user']</value>
      <webElementGuid>e869d266-497b-4260-9db6-31139d2f20c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
